name: PERN CI

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  ### Build Backend (Node.js)
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
        # need Node.js to run react (npm run)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Install Backend Dependencies
        working-directory: ./backend

        # npm ci instead of install?
        run: |
          npm install

      - name: Build backend
        working-directory: ./backend
        run: |
          npm run build

        # zip step-- compress artifact (too large)
      - name: Zip Artifact Before Uploading
        working-directory: ./backend
        run: zip release.zip ./* -r

        # upload to be used later in the process
      - name: Upload Backend Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend-build-artifact
          path: backend/release.zip
          
  ### Build Frontend ###
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # need Node.js to run react (npm run)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          
      # install frontend dependencies from package.json
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
          npm install
      # build frontend
      - name: Build Frontend
        working-directory: ./frontend
        run: | 
          npm run build

      # zip step-- compress artifact (too large)
      - name: Zip Artifact Before Uploading
        working-directory: ./frontend
        run: zip release.zip ./* -r

      # upload to be used later in the process
      - name: Upload Frontend Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build-artifact
          path: frontend/release.zip

      
